<?php

return [
    'admin_email' => 'juninhosh2013sh@gmail.com',
    'defaults' => [
        [
            'slug' => 'course-catalog',
            'eyebrow' => 'Web App',
            'title' => 'Course Catalog',
            'image_path' => 'assets/img/portfolio/cursos_full_stack.png',
            'live_url' => 'https://www.juninnzxtec.com.br/all-portifolios/site2/',
            'details_url' => 'projeto',
            'detail_category' => 'Course Catalog',
            'detail_client' => 'N/A',
            'detail_project_date' => '10 March, 2020',
            'detail_heading' => 'Why this system was created',
            'detail_body' => "This system was created for study and portfolio purposes.\nIt was built with HTML5, CSS, Bootstrap, PHP, and JavaScript, and it allows users to create, edit, and delete courses from a list.\nAll changes are saved to the database in real time after each action is confirmed.",
            'detail_images' => [
                'assets/img/portfolio/cursos_full_stack.png',
                'assets/img/portfolio/cursos_full_stack_1.png',
                'assets/img/portfolio/cursos_full_stack_2.png',
                'assets/img/portfolio/cursos_full_stack_3.png',
            ],
            'display_order' => 10,
            'is_visible' => true,
        ],
        [
            'slug' => 'financial-services-website',
            'eyebrow' => 'Website',
            'title' => 'Financial Services Website',
            'image_path' => 'assets/img/portfolio/portifolio.png',
            'live_url' => 'https://www.juninnzxtec.com.br/all-portifolios/site/',
            'details_url' => 'projeto-1',
            'detail_category' => 'Business Website',
            'detail_client' => 'N/A',
            'detail_project_date' => '10 March, 2020',
            'detail_heading' => 'Why this project was created',
            'detail_body' => "This project was originally developed to present the work and services offered by a company.\nHowever, because the company closed its operations after financial difficulties, the project was never completed.\n\nI decided to keep it as part of my portfolio after removing confidential and copyright-sensitive material.\nIt now serves as a demonstration of my skills and ability to build complete web solutions.\n\nThis project was developed using HTML5, CSS, Bootstrap, PHP, and JavaScript.\nThe design is responsive, ensuring an optimized browsing experience across different devices.",
            'detail_images' => [
                'assets/img/portfolio/imp_finc(1).png',
                'assets/img/portfolio/imp_finc(2).png',
                'assets/img/portfolio/imp_finc(3).png',
                'assets/img/portfolio/imp_finc(4).png',
                'assets/img/portfolio/imp_finc(5).png',
                'assets/img/portfolio/imp_finc(6).png',
            ],
            'display_order' => 20,
            'is_visible' => true,
        ],
        [
            'slug' => 'task-management-system',
            'eyebrow' => 'Web App',
            'title' => 'Task Management System',
            'image_path' => 'assets/img/portfolio/crud3.png',
            'live_url' => 'https://www.juninnzxtec.com.br/login',
            'details_url' => 'projeto-2',
            'detail_category' => 'Task Management System',
            'detail_client' => 'N/A',
            'detail_project_date' => '03 February, 2025',
            'detail_heading' => 'Why this system was created',
            'detail_body' => "This project was created to showcase my Laravel skills.\n\nIt was developed using Laravel, Blade, Bootstrap, PHP, CSS, jQuery, SweetAlert, and JavaScript.\nIt includes login, registration, password recovery, profile editing, logout, category creation, and full CRUD for tasks.\n\nThe design is responsive, ensuring an optimized browsing experience across different devices.",
            'detail_images' => [
                'assets/img/portfolio/crud3.png',
                'assets/img/portfolio/crud.png',
                'assets/img/portfolio/crud1.png',
                'assets/img/portfolio/crud2.png',
            ],
            'display_order' => 30,
            'is_visible' => true,
        ],
        [
            'slug' => 'product-catalog-dashboard',
            'eyebrow' => 'Vue App',
            'title' => 'Product Catalog Dashboard',
            'image_path' => 'assets/img/portfolio/crud2.png',
            'live_url' => 'https://www.juninnzxtec.com.br/all-portifolios/projectvite/',
            'details_url' => 'projeto-3.html',
            'display_order' => 40,
            'is_visible' => true,
        ],
        [
            'slug' => 'hit-dig-presentation',
            'eyebrow' => 'Landing Page',
            'title' => 'HIT DIG Presentation',
            'image_path' => 'assets/img/portfolio/imp_finc(2).png',
            'live_url' => 'https://www.juninnzxtec.com.br/all-portifolios/hitdig/',
            'details_url' => 'projeto-4.html',
            'display_order' => 50,
            'is_visible' => true,
        ],
        [
            'slug' => 'meta-locadora-control-center',
            'eyebrow' => 'Fleet Platform',
            'title' => 'Meta Locadora Control Center',
            'image_path' => 'assets/img/portfolio/app-1.jpg',
            'live_url' => 'https://controledefrotas.juninnzxtec.com.br/',
            'details_url' => 'projeto-5.html',
            'display_order' => 60,
            'is_visible' => true,
        ],
        [
            'slug' => 'finance-crm-system-preview',
            'eyebrow' => 'System Preview',
            'title' => 'Finance and CRM System Preview',
            'image_path' => 'assets/img/portfolio/product-2.jpg',
            'live_url' => 'https://www.juninnzxtec.com.br/all-portifolios/finance-system/',
            'details_url' => 'projeto-6.html',
            'display_order' => 70,
            'is_visible' => true,
        ],
        [
            'slug' => 'market-decision-ai',
            'eyebrow' => 'Trading Intelligence',
            'title' => 'Market Decision AI',
            'image_path' => 'assets/img/portfolio/branding-2.jpg',
            'live_url' => 'https://roboiqopition.juninnzxtec.com.br/',
            'details_url' => 'projeto-8.html',
            'display_order' => 80,
            'is_visible' => true,
        ],
        [
            'slug' => 'wordpress-personal-portfolio',
            'eyebrow' => 'Personal Website',
            'title' => 'WordPress Personal Portfolio',
            'image_path' => 'assets/img/portfolio/Portifolio1.png',
            'live_url' => 'http://my-portolio.juninnzxtec.com.br/',
            'details_url' => 'projeto-7.html',
            'display_order' => 90,
            'is_visible' => true,
        ],
        [
            'slug' => 'products-api-mirror',
            'eyebrow' => 'API Service',
            'title' => 'Products API Mirror',
            'image_path' => 'assets/img/portfolio/product-3.jpg',
            'live_url' => 'https://www.juninnzxtec.com.br/all-portifolios/api/',
            'details_url' => 'https://www.juninnzxtec.com.br/all-portifolios/api/',
            'display_order' => 100,
            'is_visible' => true,
        ],
        [
            'slug' => 'vite-demo-website',
            'eyebrow' => 'Landing Page',
            'title' => 'Vite Demo Website',
            'image_path' => 'assets/img/portfolio/product-1.jpg',
            'live_url' => 'http://vite.juninnzxtec.com.br/',
            'details_url' => 'http://vite.juninnzxtec.com.br/',
            'display_order' => 110,
            'is_visible' => true,
        ],
        [
            'slug' => 'positivus-website',
            'eyebrow' => 'Marketing Website',
            'title' => 'Positivus Website',
            'image_path' => 'assets/img/portfolio/Portifolio2.png',
            'live_url' => 'http://positivus.juninnzxtec.com.br/',
            'details_url' => 'http://positivus.juninnzxtec.com.br/',
            'display_order' => 120,
            'is_visible' => true,
        ],
        [
            'slug' => 'positivus-test-website',
            'eyebrow' => 'Test Environment',
            'title' => 'Positivus Test Website',
            'image_path' => 'assets/img/portfolio/portifolio.png',
            'live_url' => 'http://positivustest.juninnzxtec.com.br/',
            'details_url' => 'http://positivustest.juninnzxtec.com.br/',
            'display_order' => 130,
            'is_visible' => true,
        ],
    ],
];
